# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.requestGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.requestGroupBox.setGeometry(QtCore.QRect(10, 20, 781, 181))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.requestGroupBox.setFont(font)
        self.requestGroupBox.setAutoFillBackground(True)
        self.requestGroupBox.setObjectName("requestGroupBox")
        self.requestSpinBox = QtWidgets.QSpinBox(self.requestGroupBox)
        self.requestSpinBox.setGeometry(QtCore.QRect(320, 50, 131, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.requestSpinBox.setFont(font)
        self.requestSpinBox.setObjectName("requestSpinBox")
        self.timeoutDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.requestGroupBox)
        self.timeoutDoubleSpinBox.setEnabled(False)
        self.timeoutDoubleSpinBox.setGeometry(QtCore.QRect(320, 100, 131, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeoutDoubleSpinBox.setFont(font)
        self.timeoutDoubleSpinBox.setObjectName("timeoutDoubleSpinBox")
        self.label = QtWidgets.QLabel(self.requestGroupBox)
        self.label.setGeometry(QtCore.QRect(230, 50, 59, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.requestGroupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 281, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.timeoutCheckBox = QtWidgets.QCheckBox(self.requestGroupBox)
        self.timeoutCheckBox.setGeometry(QtCore.QRect(470, 100, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeoutCheckBox.setFont(font)
        self.timeoutCheckBox.setObjectName("timeoutCheckBox")
        self.sendRequesPushButton = QtWidgets.QPushButton(self.requestGroupBox)
        self.sendRequesPushButton.setGeometry(QtCore.QRect(620, 140, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendRequesPushButton.setFont(font)
        self.sendRequesPushButton.setObjectName("sendRequesPushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 781, 381))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(70, 50, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(40, 80, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stateRequestLabel = QtWidgets.QLabel(self.groupBox_2)
        self.stateRequestLabel.setGeometry(QtCore.QRect(292, 50, 300, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stateRequestLabel.setFont(font)
        self.stateRequestLabel.setObjectName("stateRequestLabel")
        self.requestResultLabel = QtWidgets.QLabel(self.groupBox_2)
        self.requestResultLabel.setGeometry(QtCore.QRect(292, 80, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.requestResultLabel.setFont(font)
        self.requestResultLabel.setObjectName("requestResultLabel")
        self.cancelRequestPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.cancelRequestPushButton.setGeometry(QtCore.QRect(620, 50, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelRequestPushButton.setFont(font)
        self.cancelRequestPushButton.setObjectName("cancelRequestPushButton")
        self.logsPlainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.logsPlainTextEdit.setGeometry(QtCore.QRect(30, 140, 721, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.logsPlainTextEdit.setFont(font)
        self.logsPlainTextEdit.setReadOnly(True)
        self.logsPlainTextEdit.setObjectName("logsPlainTextEdit")
        self.settingsPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.settingsPushButton.setGeometry(QtCore.QRect(30, 330, 721, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.settingsPushButton.setFont(font)
        self.settingsPushButton.setObjectName("settingsPushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Клиент"))
        self.requestGroupBox.setTitle(_translate("MainWindow", "Запрос"))
        self.label.setText(_translate("MainWindow", "Число:"))
        self.label_2.setText(_translate("MainWindow", "Время обработки запроса, сек:"))
        self.timeoutCheckBox.setText(_translate("MainWindow", "Задействовать"))
        self.sendRequesPushButton.setText(_translate("MainWindow", "Отправить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Состояние обработки запроса "))
        self.label_3.setText(_translate("MainWindow", "Состояние:"))
        self.label_4.setText(_translate("MainWindow", "Ответ сервера:"))
        self.stateRequestLabel.setText(_translate("MainWindow", "Неопределено"))
        self.requestResultLabel.setText(_translate("MainWindow", "Неопределено"))
        self.cancelRequestPushButton.setText(_translate("MainWindow", "Отмена"))
        self.settingsPushButton.setText(_translate("MainWindow", "Настройки"))
