# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertiesUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(455, 252)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 200, 341, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.brokerAddresTextEdit = QtWidgets.QTextEdit(Dialog)
        self.brokerAddresTextEdit.setGeometry(QtCore.QRect(230, 30, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.brokerAddresTextEdit.setFont(font)
        self.brokerAddresTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brokerAddresTextEdit.setAcceptRichText(True)
        self.brokerAddresTextEdit.setObjectName("brokerAddresTextEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(21, 22, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(93, 66, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.exchangeNameTextEdit = QtWidgets.QTextEdit(Dialog)
        self.exchangeNameTextEdit.setGeometry(QtCore.QRect(230, 70, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exchangeNameTextEdit.setFont(font)
        self.exchangeNameTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.exchangeNameTextEdit.setObjectName("exchangeNameTextEdit")
        self.clientUuidTextEdit = QtWidgets.QTextEdit(Dialog)
        self.clientUuidTextEdit.setGeometry(QtCore.QRect(230, 110, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clientUuidTextEdit.setFont(font)
        self.clientUuidTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.clientUuidTextEdit.setObjectName("clientUuidTextEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(95, 108, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(18, 151, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.connectionTimeoutDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.connectionTimeoutDoubleSpinBox.setGeometry(QtCore.QRect(230, 150, 201, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.connectionTimeoutDoubleSpinBox.setFont(font)
        self.connectionTimeoutDoubleSpinBox.setObjectName("connectionTimeoutDoubleSpinBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки конфигурации"))
        self.label.setText(_translate("Dialog", "Адрес и порт брокера"))
        self.label_2.setText(_translate("Dialog", "Имя exchange"))
        self.label_3.setText(_translate("Dialog", "UUID клиента"))
        self.label_4.setText(_translate("Dialog", "Таймаут подключения"))
